### ISSUE TITLE
How to maintain a custom nav structure

### ISSUE THREAD

**Issue by oskarrough** [bryanbraun/middleman-navtree#1]
middleman-navtree automatically (over)writes a `tree.yml` reflecting the structure in `/source` which is great. What is the recommened way of maintaining a custom structure? Say a different ordering if you're files aren't prefixed with a number.

Copy/paste the tree.yml, duplicate it and modify it and reference it in config.rb in the navtree settings?

And thanks for the great plugin!

**Comment by bryanbraun** [comment]
@assimovt submitted [a pull request](https://github.com/bryanbraun/middleman-navtree/pull/5) that included an option to manually manage the tree.yml file. It's described [here](https://github.com/bryanbraun/middleman-navtree/pull/5#issue-52773298) in detail.

In short, you get an option to prevent further updates to tree.yml, once the file has been generated. That way you can manually edit it to use whatever Titles and URLs you want.

I liked the approach, so after a bit of discussion I went ahead and integrated it. The README.md has been updated to include this new option and I've pushed it up to rubygems as part of the [middleman-navtree 0.1.9 version](https://rubygems.org/gems/middleman-navtree/versions/0.1.9). 

I'm considering this issue closed. Thanks for the great discussion and resolution!
