### ISSUE TITLE
Labels need translations

### ISSUE THREAD

**Issue by pyrog** [bryanbraun/middleman-navtree#9]
Labels **Previous** and **Next** of Pagination helpers need to be localized

**Comment by bryanbraun** [comment]
Hmm. Good call. It looks like middleman requires the i18n gem, and we can probably use the  `I18n.t()` function for translation, as described here: https://middlemanapp.com/advanced/localization/#localization-(i18n)

I can't get around to this immediately, but be my guest if you (or anybody else) wants to take a crack at it.

**Comment by bryanbraun** [comment]
Thanks to some help by @musashimm, this issue was fixed by https://github.com/bryanbraun/middleman-navtree/pull/19.

Closing.
